// export const API_HOST_NAME = 'https://demo-production-627b.up.railway.app/api/'
export const API_HOST_NAME = 'https://demo-jg34.onrender.com/api/'
// export const API_HOST_NAME = 'http://localhost:8080/api/'
// export const HOST_NAME = 'http://localhost:8080'
export const HOST_NAME = 'https://demo-jg34.onrender.com'